### ISSUE TITLE
Automatic string formatters a-la Angular filter

### ISSUE THREAD

**Issue by moshewe** [xsolla/currency-format#1]
I've seen you've also implemented an angular filter utilizing this JSON [here](https://github.com/xsolla/angular-currency-format).

Would you mind if I add the filter formatting code to this package so that it will be available for non-angular usage?

**Comment by apigraf** [comment]
Hi
This package is used not only in the JS projects, and it is intended only for storing information about the currency (in JSON).
But you can create a new package, in which the filter will be implemented.

Thanks for the suggestion.
