### ISSUE TITLE
Add local separators

### ISSUE THREAD

**Issue by karthikiyengar** [xsolla/currency-format#13]
Hi,

Thanks for this.

Would it be possible to add separators to this list? For instance `EUR` would be separated by `,`

**Comment by a-treschilov** [comment]
Hi,

you can use https://github.com/xsolla/currency-number-format with this library for thousands and decimal separators.

This is separate library, because separators are area preferences, that not depends of currency.

**Comment by karthikiyengar** [comment]
Thanks, that makes sense :-)
