### ISSUE TITLE
Swiss Franc template

### ISSUE THREAD

**Issue by peterpeterparker** [xsolla/currency-format#6]
Hi,

First of all, thx for the json, was looking for something like this since ages!

I've got a request about the swiss franc template. If I understand correctly, a template like "$1" means "symbol" and then "value" (like $1534.32).

In case of the swiss franc, your current template is "$1" which is, I think, not correct. 
It should be "1 $" like "1534.32 CHF".

Are you agree? Or where did you found an official description of these template?

Thx you in advance for your feedback

**Comment by apigraf** [comment]
Hi,
We have removed a swiss franc symbol (commit 01e3942). The default entry used "<amount> <ICO code>" (for example: 1534.32 CHF).
Thank you.
